### ISSUE TITLE
can't submit multiple brands

### ISSUE THREAD

**Issue by ghost** [learn-co-curriculum/oo-basics-with-class-constants#9] opened 2016-06-28 13:33 UTC
hello, I just worked on this problem with Adam

this is a little confusing..
the purpose of this exercise is to be able to push multiple brands to the BRANDS constant
but it doesn't actually accomplish this
Adam told me it defeats the purpose of a constant and should be a class variable "@@" in a self class.
since this is not something we've covered yet, I thought I would raise an issue.
thanks!

**Comment by pletcher** [comment] 2016-06-28 13:33
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!

**Comment by ghost** [comment] 2016-06-28 13:40
@pletcher ok so, specifically
if you set up
i = Shoe.new("j")
it returns as it should
from what I understand about this lesson, the purpose is to be able to add multiple brands
but the only way I could figure out how to add more content is to use
i.brand.split << "k"
and from what Adam told me, I shouldn't have to do this, and should be able to call
i.brand("k")
so he told me the constant should be a "@@" class variable, and brand should be a "self" method

and since we have not covered this material yet, I thought it would be valuable to other students to raise an issue.

as far as all the other stuff you wrote, "no"

**Comment by pletcher** [comment] 2016-06-28 14:11
Hi @tripscripts,

You're right that this isn't exactly how we should use constants, but for these purposes it's okay (we introduce class variables later on).

A very basic outline of your shoe class should look something like

``` ruby
class Shoe
  BRANDS = []

  def initialize(brand)
    @brand = brand
    BRANDS << brand unless BRANDS.include?(brand)
  end
end
```

So I'm not sure why you're having to split `i.brand` -- you aren't adding additional brands to an instance of a `Shoe`, but rather to the entire `Shoe` class.

I'm going to close this before it gets too out of band. Please follow up with the Learn experts if you continue to run into trouble.

**Closed as completed by pletcher** 2016-06-28 14:11 UTC

**Comment by ghost** [comment] 2016-06-28 14:27
@pletcher right, this is what I have. I completed the lesson earlier this morning, and I passed all of the RSPEC tests, but the class doesn't behave as it should. if you run 
i.brand("k") or i.brand = "k"
it returns an error
and with
i.brand << "k" 
it returns a concatenated string "jk" instead of ["j", "k"]
that's why I had to use split

I'm not sure what you mean by out of hand. I'm only bringing this up to benefit future students, which I thought was the point of raising an issue. The whole reason I posted this, is because I already consulted one of the teachers. I mentioned him in my original post. "Adam" told me that I should rightfully raise this issue. 

I hope to hear your further feedback.

**Comment by pletcher** [comment] 2016-06-28 14:38
Hi @tripscripts,

That's right, `i.brand << "j"` won't work because `i.brand` is an instance
variable, and you want to update the constant `BRANDS` (which you can only
access by initializing another `Shoe`).

Does that make sense?

We appreciate you opening the issue -- by "out of hand" I just meant that I
didn't want my explanation to veer off into the ether.

**Comment by ghost** [comment] 2016-06-28 14:53
@pletcher but by initializing an additional Shoe you will lose the "brand" contents from the other Shoe.

like I mentioned, I was under the impression that the function of this class was to be able to store multiple brand types. hence the attr_reader, and then this separate setter method.

the README file says "complete the exercise where the Shoe class can keep track of all the brands"

man, believe me, you aren't going to veer off on me. I'm super interested, and eager to learn.
I sincerely appreciate your time, realize you are busy, and hope you can help me figure out where I'm going wrong here.. not for the purpose of passing the RSPEC tests, but for personal enrichment about the capabilities we're discussing.

**Comment by pletcher** [comment] 2016-06-28 15:15
Hi @tripscripts

That's the thing: `attr_accessor` works with _instances_ of `Shoe`, but the `Shoe` class contains the constant `BRANDS`. So when the README says, "complete the exercise where the Shoe class can keep track of all the brands," it means the actual _class_ and not any individual instance thereof.

For example, we have your `Shoe` class

``` ruby
class Shoe
  attr_accessor :color, :size, :material, :condition
  attr_reader :brand

  BRANDS = []

  def initialize(brand)
    @brand = brand
    BRANDS << brand unless BRANDS.include?(brand)
  end

  def cobble
    @condition = "new"
    puts "Your shoe is as good as new!"
  end
end
```

And we initialize a shoe:

``` ruby
tennis_shoe = Shoe.new("tennis")
```

We can see that this individual shoe's brand is `'tennis'` by entering `tennis_shoe.brand`.

But we can also see that the `Shoes` class now has a brand in the `BRANDS` array:

``` ruby
Shoe::BRANDS # ["tennis"]
```

This is just like accessing `GENRES` on the `Book` class in the lesson.

We can then initialize another shoe:

``` ruby
running_shoe = Shoe.new('running')
```

Again, we can see this shoe's brand (`'running'`) with `running_shoe.brand`.

And we can also see that `Shoe::BRANDS` has updated:

``` ruby
Shoe::BRANDS # ["tennis", "running"]
```

So that seems to be where the confusion is. Play around with the code a bit in `irb`, and make sure that it's clear what is the responsibility of the _instance_ (hint: it's anything in `attr_reader` or `attr_accessor`) and what is the responsibility of the _class_.

**Comment by ghost** [comment] 2016-06-28 15:36
ahhhhh!!! so Shoe::BRANDS
ok I went back over the readme file and it does discuss "name spacing"
I feel like I understand this concept well now

thanks for all of the time you spent explaining that to me!
